.TH extract-fchk-pts 1 "2020" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-fchk-pts

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-fchk-pts FILE

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Extract coordinates, energy, and optionally gradient and Hessian from formated Gaussian checkpoint file FILE. Results are printed to the standard output in the PTS format for the FFDevel package.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B FILE
.RS
Gaussian formatted checkpoint file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-ene(1), extract-gdrv-xyz(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2020 Petr Kulhanek, kulhanek@chemi.muni.cz
