.TH extract-xyz-numstr 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract_xyz_numstr

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gopt-xyz <file.xyz>

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints the number of structure snapshots included in file.xyz. The result is printed to the standard output.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B file.xyz
.RS
multiple-xyz file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-xyz(1), extract-gopt-xyz(1), extract-xyz-str(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz