.TH extract-gdrv-pts 1 "2020" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-gdrv-pts

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gdrv-pts FILE

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints system coordinates along a prescribed reaction coordinate including driven coordinates from the potential energy scanning calculation performed by Gaussian. Results are printed to the standard output in the multiple PTS format for the FFDevel package.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B FILE
.RS
Gaussian log file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-ene(1), extract-gdrv-xyz(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2020 Petr Kulhanek, kulhanek@chemi.muni.cz
