.TH extract-gdrv-ene 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract_gdrv_ene

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gdrv-ene <gaussian.log>

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints energy values along a prescribed reaction coordinate from the potential energy scanning calculation performed by Gaussian. Results are printed to the standard output.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B gaussian.log
.RS
Gaussian output file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-xyz(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz