.TH extract-gopt-xyz 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-gopt-xyz

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gopt-xyz <gaussian.log>

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints system coordinates describing the progress of geometry optimization performed by Gaussian. Results are printed in the multiple-xyz format to the standard output.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B gaussian.log
.RS
Gaussian output file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gopt-ene(1), extract-xyz-numstr(1), extract-xyz-str(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz