.TH extract-xyz-str 1 "2020" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-xyz-str

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gopt-xyz FILE ID

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Extracts the snapshot of number ID from multiple-xyz FILE. The resulting structure is printed to the standard output in the xyz format.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B FILE
.RS
multiple-xyz file
.RE

.SH ARGUMENTS
.B ID
.RS
snapshot number (counted from 1), or 'last' keyword for the last snapshot, or 'first' keyword for the first snapshot
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-xyz(1), extract-gopt-xyz(1), extract-xyz-numstr(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2020 Petr Kulhanek, kulhanek@chemi.muni.cz
