.TH extract-xyz-numstr 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-gopt-xyz

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gopt-xyz FILE

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints the number of structure snapshots included in FILE. The result is printed to the standard output.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B FILE
.RS
multiple-xyz file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-xyz(1), extract-gopt-xyz(1), extract-xyz-str(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz
