.TH extract-gdrv-ene 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
extract-gdrv-ene

.\"-----------------------------------------------------------------------------
.SH SYNOPSIS
extract-gdrv-ene FILE

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
Prints energy values along a prescribed reaction coordinate from the potential energy scanning calculation performed by Gaussian. Results are printed to the standard output.

.\"-----------------------------------------------------------------------------
.SH ARGUMENTS
.B FILE
.RS
Gaussian log file
.RE

.\"-----------------------------------------------------------------------------
.SH SEE ALSO
qmutil(1), extract-gdrv-xyz(1), extract-gdrv-pts(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz
