.TH qmutil 1 "2008" "QMUtil" "QMUtil - miscellaneous utilities for QM programs"

.\"-----------------------------------------------------------------------------
.SH NAME
qmutil

.\"-----------------------------------------------------------------------------
.SH DESCRIPTION
qmutil is the set of miscellaneous utilities designed for a manipulation with output files from various quantum-chemical programs. Currently, the most supported program is Gaussian.


.\"-----------------------------------------------------------------------------
.SH SEE ALSO
extract-gdrv-ene(1), extract-gdrv-xyz(1), extract-gopt-ene(1), extract-gopt-xyz(1), extract-xyz-numstr(1), extract-xyz-str(1), gamdens2mopdens(1), gxxdens2gamdens(1), xyzmulifit(1)

.\"-----------------------------------------------------------------------------
.SH COPYRIGHT
Copyright (c) 2008 Petr Kulhanek, kulhanek@chemi.muni.cz